# Generated by Django 5.0 on 2024-01-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publication', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('price', models.PositiveIntegerField()),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('shelf_no', models.PositiveIntegerField()),
                ('isbn', models.CharField(blank=True, editable=False, max_length=13, unique=True)),
                ('cover_image', models.URLField()),
            ],
        ),
    ]
